### ISSUE TITLE
请问这个代码是哪本书里的啊？谢谢啦

### ISSUE THREAD

**Issue by Algo-Goer** [PRML/PRMLT#52]
看到有chapter，想问问博主，这是什么书籍的代码？谢谢！

**Comment by ZZKnight** [comment]
Pattern Recognition and Machine Learning, by Bishop
https://g.co/kgs/q6cNmV

**Comment by Algo-Goer** [comment]
> Pattern Recognition and Machine Learning, by Bishop https://g.co/kgs/q6cNmV

Many thanks！

**Comment by TinkerLee** [comment]
Pattern recognition and machine learning







At 2021-10-28 17:12:02, "Algo-Goer" ***@***.***> wrote:

Closed #52.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
